### ISSUE TITLE
Roadmap and Planned Features

### ISSUE THREAD

**Issue by geoffrey45** [geoffrey45/alice#74]
### Discussed in https://github.com/geoffrey45/alice/discussions/72

<div type='discussions-op-text'>

<sup>Originally posted by **geoffrey45** June 14, 2022</sup>
# Alice Roadmap and Planned Features

### ✨ Completed
- [x] **Browse folders**
Browse through your music library using a file manager like interface.
- [x] **Album page**
Click on an album title to view the album's other tracks, bio and featured artists.
- [x] **Playlist pages**
Create and edit your playlist by going to the playlist page from the left sidebar.
- [x] **Queue**
Manage your currently queue from the right sidebar
- [x] **Context menu**
Right click on a track item to possible actions like adding a track to queue, adding to playlist, and others.
- [x] MongoDB
MongoDB is used as the default database. SQLite database support after alpha release.
---
###  🛠️ Work in progress
- [x] **Global Search**
Search through your library for tracks, albums, artists and playlists.

`Sub tasks`

- [ ] Add playlists to global search
- [ ] Add top results tab to search

---
### ⏭️ Next in line

- [ ] Implement dummy context actions
Write logic for those context menus that print to the console.
- [ ] Remove dummy components
Open a new release branch and remove dummy UI components, eg. those page search inputs.
---
- [ ] 🎉 **Release: v0.0.1.alpha** 🎉
---
### ⏭️ Next in line
- [ ] Page search
Filter page content by typing through an input field at the top of the page.</div>
